spring:
  datasource:
    url: jdbc:h2:mem:payments;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  h2:
    console:
      enabled: true
notification:
  type1-url: "http://localhost:8080/external/type1?payment_id="
  type2-url: "http://localhost:8080/external/type2?payment_id="
  type1-cancel-url: "http://localhost:8080/external/type2/cancel?payment_id="
  type2-cancel-url: "http://localhost:8080/external/type2/cancel?payment_id="

cancellation:
  type1-fee: 0.05
  type2-fee: 0.10
  type3-fee: 0.15

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
  level:
    root: INFO